name: rounded_letter
description: Letter inside circle
version: 0.0.2
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/roundedletter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.jhomlala.roundedletter
    pluginClass: RoundedLetterPlugin
